version: "3.8"

services:
  white_cloud:
    image: captainhoangle/white_cloud:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /root/ssl/conf:/etc/letsencrypt
      - /root/ssl/www:/var/www/certbot
    depends_on:
      - white_cloud
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
